### ISSUE TITLE
Descripcion de los Items

### ISSUE THREAD

**Issue by delucas** [3DRealms/jrpg#8]
Probablemente les convenga almacenar las descripciones de los items en archivos de propiedades, o incluso en la base de datos.
Me refiero [a esto](https://github.com/3DRealms/jrpg/blob/master/dominio/src/main/java/itemEquipo/AnilloDraupnir.java#L9).

**Comment by DrCoffee84** [comment]
llegado el dia lo sacare y lo pondremos en la BD
