### ISSUE TITLE
Sobre variables de un solo uso

### ISSUE THREAD

**Issue by delucas** [3DRealms/jrpg#9]
Estimo que esto es un WIP, pero...
en [este caso](https://github.com/3DRealms/jrpg/blob/master/dominio/src/main/java/personaje/ExperienciaRequerida.java#L8), la variable `nivel` sería innecesaria:

``` java
private int enQueNivel(int experienciaActual) {
    int nivel=0;
    return nivel;
}
```

**Comment by DrCoffee84** [comment]
Esto era de algún commit viejo, porque ya no lo encuentro.
